### ISSUE TITLE
Move ~/QGIS/Resource Sharing to ~/.qgis2/resource_sharing/

### ISSUE THREAD

**Issue by borysiasty** [QGIS-Contribution/QGIS-ResourceSharing#51]
I guess I'm not the only one who immediately remove such directories that clutter my home dir,
what unfortunately casuses the nasty error #43 ;)

Moving the directory into .qgis2/resouce_sharing would:
  - Protect it from being hastily deleted by spitfires and lock the plugin

  - The opposite: allow to clear all local data by removing just one directory, easy to find in an expected location. 

  - Make the home dir clean and the user happy :tada:

What do you think about it?

**Comment by akbargumbira** [comment]
hi @borysiasty, there was a reason for this, but I kind of forget it. @elpaso @anitagraser do you still remember it? if not I'll try to dig our conversation..

**Comment by anitagraser** [comment]
No idea, sorry.

**Comment by akbargumbira** [comment]
Hi @borysiasty, so after digging up old emails, I found that I implemented it the first time as you said (https://github.com/akbargumbira/qgis_resources_sharing/commit/9bde1af4386c76801853459eb1174f32995f6a9f). It seems that one of the problems is stated here https://github.com/akbargumbira/qgis_resources_sharing/commit/0b32376ea046410a31c07affa0d5fa7016768342#diff-e36671ccdb491b73a1e066ecac92bcaeR127, that all the SVG resources would be under 'User Symbols' in SVG selector GUI (I guess it was preferred that all the resources from this plugin are under another tree)

**Comment by borysiasty** [comment]
Ach, we have a little mess here. *User Symbols*'s tooltip states it's ~/.qgis2/svg, however, in fact, it collects everything from withinh ~/.qgis2// (note the double slash; ~/.qgis2/resource_sharing/Foo will be a top-level branch (at least in Linux), as it doesn't have the double slash! ;) ). And, in my case, running from build dir created two invalid paths in addition.

Ok, so let's wait until the Resource Sharing is ported to core. Then we can decide how to handle it (and probably add a simple migration tool). For now I'll be just patching my installation ;p

Feel free to close the ticket or keep it open for the future merge.

**Comment by Gustry** [comment]
I just tried the QGIS 3 version. Thanks @havatv for the port.

With the move to QGIS 3, is-it still not possible to move somewhere in `~/.local/share/QGIS`?

At least, can we make it hidden?

**Comment by havatv** [comment]
With 0.9.0, the R scripts are placed in ~/.local/share/QGIS/QGIS3/profiles/default/processing/rscripts/ on Linux  (and the corresponding folder on Windows), and the scripts shall automatically show up in the Processing toolbox. That is what happens here, anyway (Ubuntu 18.04, QGIS 3.4 and 3.10).
So if you experience something else, that is a bug.

**Comment by Gustry** [comment]
So you are referring only to R scripts for now?
For symbology, it's still in the home folder today

**Comment by havatv** [comment]
@Gustry, sorry for not answering your question (I have only been working on the R scripts, so I assumed that you were asking about that (did not notice which issue this was in...).
I can try change the location of the resources for the other types as well (Python scripts should be OK, but SVGs and images probably need some love).

**Comment by Gustry** [comment]
> I can try change the location of the resources for the other types as well (Python scripts should be OK, but SVGs and images probably need some love).

Ok. At least to make the folder hidden?

I think it's very bad to add folders in the home folder visible.

```bash
~ $ ls -l ~/QGIS/Resource\ Sharing/
total 4
drwxr-xr-x 5 etienne etienne 4096 févr. 16 20:16 'Dimensions (58846ed8096903ce1e004506407ba45c6b6bb6b9)'
```

**Comment by havatv** [comment]
I have not preferences when it comes to where under ``~/.local/share/QGIS/QGIS3/profiles/default/`` to place the other resources, so good ideas are very welcome!

**Comment by borysiasty** [comment]
Thanks a lot!

**Comment by havatv** [comment]
Thanks, @borysiasty.
If you have time to test this, it would be great. We may be able to do some more polishing before we release a new version of the plugin with this PR included.  @elpaso has suggested that we use QgsSettings instead of QSettings. I will look into that soon.
The documentation should already be updated (http://qgis-contribution.github.io/QGIS-ResourceSharing). Feel free to comment on that also.

**Comment by borysiasty** [comment]
@havatv  I'm sorry I wish I could contribute, but I'm *totally* out of time for upcoming months :( Even for such a small test, as the whole backlog is made of small things...

**Comment by havatv** [comment]
Don't worry, @borysiasty. Your input has already been valuable.
